### PR TITLE
Move 'other HOCON tools' to HOCON.md

### PR DESCRIPTION
**Pull request by raboof**
As they're relevant to everyone interested in HOCON, not specifically Typesafe
Config users

### CODE REVIEW

**Comment by raboof** [comment]
(rebased to fix conflict with https://github.com/lightbend/config/pull/525)

**Comment by havocp** [comment]
I’m a bit worried this lowers exposure and visibility for these tools, though I don’t have analytics to prove it, I’d imagine README gets more views. Maybe the README could be more explicit in saying that implementations for other languages can be found at this link?

**Comment by raboof** [comment]
Yes, I agree with that concern. My intent was in fact the opposite: I'm afraid someone not interested in Scala will see the README, assume it's "just some Scala library" and not get to this part at all. Similarly, someone who just googles for 'hocon' will find https://github.com/lightbend/config/blob/master/HOCON.md first and also miss these links.

I agree putting this in `HOCON.md` seems a bit 'buried'. I wonder if it'd make sense to create a separate (tiny) `lightbend/hocon` project describing the format and linking to various libraries, without any scala/typesafeconfig-specific parts?

**Comment by raboof** [comment]
> I agree putting this in `HOCON.md` seems a bit 'buried'. I wonder if it'd make sense to create a separate (tiny) `lightbend/hocon` project describing the format and linking to various libraries, without any scala/typesafeconfig-specific parts?

(I'd still be willing to do this, if y'all agree it would be helpful. closing this PR though :) )

**Pull request closed without merging**
