### PR TITLE
Add new Scala port to README.md

### PR DESCRIPTION
**Pull request by ekrich**

### CODE REVIEW

**Comment by havocp** [comment]
Maybe it would be helpful to explain the difference between the two scala ports; I don't want to do it in a way that makes anyone annoyed, but both of them work with scala.js as in the parens on SHocon right?

**Comment by ekrich** [comment]
Right now it only supports JVM so I didn't want to say anything that might change in the future. If you go to the page it explains things clearly I hope.

@andreaTP I think you know about `sconfig`, can you weigh in on the subject?

**Comment by andreaTP** [comment]
@ekrich I'm really happy to see your effort going on! amazing!

Actually I would need to update information around Shocon:
this is the new correct address: https://github.com/akka-js/shocon
and it supports both Scala.Js and Scala Native.

From my POV `sconfig` is a port to Scala of Typesafe config while, in fact, `shocon` is a Scala re-implementation of the HOCON specification with a thin layer of API compatibility.

That said, I'll let you word it appropriately or leave it as proposed by @ekrich , as there are several Scala wrappers with no additional explanation on the differences already.

**Comment by ekrich** [comment]
@andreaTP Thanks, really appreciate the kind words. Do you want me to update yours in this PR?
@havocp I can add that it is a direct port to Scala of the `config` library if that makes it more clear.

**Comment by andreaTP** [comment]
@ekrich as you prefer, appreciated if you do so, otherwise I will follow up! :smile:

**Comment by ekrich** [comment]
@havocp and @andreaTP I decided I'd rather just leave the link for `sconfig` but made some updates for `SHocon`. Let me know if they are ok.

**Comment by andreaTP** [comment]
LGTM thanks for the update!

**Comment by havocp** [comment]
cool thanks for talking it over

**Pull request merged**
