### PR TITLE
Support wildcard include using glob syntax

### PR DESCRIPTION
**Pull request by radist-nt**
Implemented syntax proposed in #639:
include glob("confdir/*.conf")

### CODE REVIEW

**Comment by radist-nt** [comment]
@havocp, could you see this PR? It introduces the new include syntax which could be usefull in some cases and should not brake any current usage.

**Comment by Thermi** [comment]
@havocp It would be great if it was merged

**Comment by thibaultmeyer** [comment]
@havocp, @av-elier
Any ETA when this PR will be review ?

**Comment by av-elier** [comment]
I'am not a maintaiter at all, I committed only to readme, @thibaultmeyer. I can't help you.

**Comment by ennru** [comment]
We do not intend to extend the functionality of "Typesafe Config" further.
See https://github.com/lightbend/config#maintained-by

**Pull request closed without merging**
