### PR TITLE
Fixed support for keys that look like numbers longer than an int.

### PR DESCRIPTION
**Pull request by michalmela**
Previously such config keys would still be parsed with
`Integer#parseInt`, resulting in a `NumberFormatException`.
Now the number-like keys are parsed to a Long (no measures made but
performance expected hit expected to be negligible) if their numbers of
digits is shorter than the number of digits in `Long.MAX_VALUE`.

One could have also tried to parse numbers exactly up to `Long.MAX_VALUE`,
but added usability doesn't seem to match the required complexity - in
fact, one could also argue that the current loop-based checking if a key
looks like a number is a bit of an overkill, but I didn't want to dig into
the original reason for why a regexp was not used, instead focusing on
fixing an apparent bug in the most straightforward way.

### CODE REVIEW

**Comment by michalmela** [comment]
It was only after I made the pull request that I realized there is already an issue and a pull request open with regard to the issue I tried to solve here ( https://github.com/lightbend/config/pull/557 ).

While I greatly appreciate the effort put in the other pull request (as it definitely develops the library's extensibility in the right way), I wonder if my fix couldn't be used for a bugfix release? As I believe the `NumberFormatException` thrown on long number keys is definitely a bug, I tried to fix the bug with the minimal amount of changes in the behavior of the key parser/ordering.

Therefore, I believe my fix is rather straightforward and could be merged for a bugfix release much sooner, with little need for further discussion. The final solution, as developed in the other pull request/issue, would in time replace my fix, while not leaving a glaring bug in the library in the meantime.

What do you think?

**Comment by havocp** [comment]
Sorry for the slow reply; I agree with separating out just the bugfix, but maybe using BigInteger is a nicer solution than checking the number of digits (so that we still sort things as numbers even when large)?

**Comment by michalmela** [comment]
Done. Now the pull request contains basically the same thing as in @mmolimar 's https://github.com/lightbend/config/pull/557 minus the comparator being configurable (which I guess is why that pull request is still being discussed) plus a tiny improvement to the unit tests. Hopefully we can get a bugfix release soon then :)

**Comment by michalmela** [comment]
I am not sure why did the Travis CI build fail, the only error message I see is "We couldn't find the repository lightbend/config" but I don't know if it's me not having some permissions to see the build or is it an actual configuration problem?

**Comment by havocp** [comment]
Maybe a transient travis bug?

Anyway the error is

info] Set current project to config-root (in build file:/home/travis/build/lightbend/config/)
[error] java.lang.RuntimeException: Switch failed: no subprojects list "2.12.8" (or compatible version) in crossScalaVersions setting.
[error] If you want to force it regardless, call ++ 2.12.8!

**Comment by michalmela** [comment]
OK, now I see the Travis logs as well! But it's the same error as in https://github.com/lightbend/config/pull/602 – an unrelated issue with the Scala version used by Travis CI (2.12.8, as seen in the error message) vs the one defined in SBT for the project and (I guess) the recent release of Scala 2.12.8.

I guess it should be an easy fix by either specifying the Scala version to use in the `.travis.yml` or bumping the project Scala version to 2.12.8. I don't know, however, if it should be done within this pull request (will certainly look counter-intuitive to anyone analyzing the git history in the future) and also which of these paths would you rather see through?

**Comment by michalmela** [comment]
Travis is finally at peace :)

**Comment by havocp** [comment]
🎉 thanks!

**Pull request merged**
