### PR TITLE
build on sbt 1.8.1 to allow for CI on Java 17

### PR DESCRIPTION
**Pull request by ennru**
Trying to update sbt for JDK 17 compatibility.

### CODE REVIEW

**Comment by ennru** [comment]
I had to disable both JaCoCo and Checkstyle as the build wouldn't work immediately. Given that we don't expect this library to evolve more, I believe that could be acceptable. WDYT @havocp ?

**Comment by havocp** [comment]
It seems fine to me as long while nobody's actively working on the library, someone could always put it back if they planned to do a round of work.  (Side note there is considerable demand for a couple months of bugfixes and small features I think, judging by the issue tracker, but I don't personally have time to triage it all and do the work right now.)

**Comment by ennru** [comment]
We can leave this hanging as a reminder to make it work again. The important bit is that it shows -- as expected -- that we don't have any issues with JDK 17.
I created #757 to finish the move to GitHub actions.

**Comment by ennru** [comment]
We do not intend to extend the functionality of "Typesafe Config" further.
See https://github.com/lightbend/config#maintained-by

**Pull request closed without merging**
