### PR TITLE
Support for Maps of any supported value type

### PR DESCRIPTION
**Pull request by kringol**
Added simple support for more than just Map<String, Object> when building a bean from the config

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kringol,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kringol** [comment]
Also added support for map key names containing dots. 
Might also be help for some people dealing with https://github.com/lightbend/config/issues/493 and bean mapping

**Comment by rasentry** [comment]
I am very expecting this exciting feature.

**Comment by kringol** [comment]
Replacing this PR with an extended and cleaner (branching) here -> https://github.com/lightbend/config/pull/654

**Pull request closed without merging**
