### PR TITLE
Never pass null ConfigOrigin to PathParser.parsePathNodeExpression

### PR DESCRIPTION
**Pull request by javaerb**
This was causing NPEs on certain parse errors while trying to construct a ConfigException

### CODE REVIEW

**Comment by javaerb** [comment]
CLA signed

**Comment by havocp** [comment]
Thanks, makes sense! Should plan to merge this before the next release. Tests would not be bad, here (potentially to verify the right error is thrown with the right line number in it), if anyone wants to take a crack at that.

**Comment by javaerb** [comment]
Thanks, and sorry, I would have loved to add a test, but my time is currently a bit limited, and I am not yet familiar with the build system.

**Comment by ktoso** [comment]
Thanks for the contrib regardless!

**Pull request merged**
