### PR TITLE
Expose the AST/CST for interation. Fixes #300

### LINKED ISSUE #300: Public access to `ConfigNode` tree
The idea here is to allow people to examine and modify the syntax tree of `ConfigDocument`.

The general plan of attack:
  * the public ConfigNode subtypes should be as high-level and semantic as possible; they should not expose the `tokens` stuff, and naming should mirror the `ConfigValue` API and hierarchy when appropriate. Likely types might be: `ConfigNodeObject`, `ConfigNodeList`, `ConfigNodeValue`, `ConfigNodeInclude`, `ConfigNodeSubstitution`, `ConfigNodeConcatenation`, `ConfigNodeComment`, `ConfigNodeText` (`ConfigNodeText` would be whitespace, colon, equals, braces, brackets, etc. - better name?)
  * these public interfaces need to be created in `com.typesafe.config.parser` and have appropriate useful methods on them: access the relevant contents of the node, copy the node with changes, etc.
  * the `impl` subtypes of `ConfigNode` need to implement the interfaces, and  probably should be renamed; the convention to date has been `SimpleFoo` for the one default implementation of `Foo`, I would really rather this was `FooImpl` or `DefaultFoo` probably, but we could stick to `Simple` for now and fix everything at once later
  * add a method to `ConfigDocument` to get the root node
  * add a `ConfigNodeFactory` with static methods to create nodes

### PR DESCRIPTION
**Pull request by patrickptibco**
This exposes an api for AST/CST interaction. I followed the general plan of attack as outlined in #300. Fixes #300

With these changes you can now edit HOCON files and preserve whitespace, comments, and variable references.

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @patrickptibco,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by patrickptibco** [comment]
I have signed the CLA

**Comment by lightbend-cla-validator** [comment]
Hi @patrickptibco,

Thank you for your contribution! We really value the time you've taken to put this together.

We see that you have signed the Lightbend Contributors License Agreement before, however, the CLA has changed since you last signed it.
Please review the new CLA and sign it before we proceed with reviewing this pull request:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

**Comment by patrickptibco** [comment]
Grr... I'd love to avoid dealing with my legal department again, what are the changes in the new CLA?

The changes since last time are just bumping down the required java version as toUnmodifiableList was 11 only, and fixing two missed tests, along with a merging of master.

**Comment by ennru** [comment]
We do not intend to extend the functionality of "Typesafe Config" further.
See https://github.com/lightbend/config#maintained-by

**Comment by kastoestoramadus** [comment]
@patrickptibco you are more that welcomed in maintained HOCON lib:
https://github.com/ekrich/sconfig
For me it was a plug and play replacement.

**Pull request closed without merging**
