### PR TITLE
Added reference to args4c for command-line-to-config utils

### PR DESCRIPTION
**Pull request by aaronp**
It seemed there wasn't a library to bridge the gap between the main entry point and running an app based on a Config.

I've added a link to consider 'args4c', which exposes some utilities for converting command-line arguments into a lightbend config

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @aaronp,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by aaronp** [comment]
Thanks! I've signed the CLAs, though it seems my PR to the readme.md broke a test ;-)

looks like checkstyle wasn't happy trying to find http://www.puppycrawl.com/dtds/configuration_1_3.dtd

**Comment by andreaTP** [comment]
@aaronp the CI is fixed here: https://github.com/lightbend/config/pull/620/files#diff-51bda85b04329ee830142c15264b6c57R4

**Comment by aaronp** [comment]
Thanks Andrea - I left a couple comments on your PR as well -- many thanks
for the great work!

**Pull request merged**
