### PR TITLE
Bean validation config to allow missing values or other settings

### PR DESCRIPTION
**Pull request by kringol**
_Continuation of https://github.com/lightbend/config/pull/602. Taking into account the feedback, etc_

The purpose of this change is to provide a mechanism to configure the bean factory internal workings, and in this particular case, to provide a setting to allow missing field values and keep whatever value was originally assigned to the bean or null, instead of throwing an a validation error.
By default such config is disabled, to keep the current behavior as it is and provide a configuration mechanism similar to other sections of the library

### CODE REVIEW

**Comment by rkhmelichek** [comment]
Are there plans to merge this pull request?
I'm also in need for a solution to #440

**Comment by kringol** [comment]
Waiting for @havocp and the team to review/approve prepare the next release i guess. Not sure about the timelines.

**Comment by avillev** [comment]
@havocp @andreaTP @johanandren @2m 

Sorry to tag that many mergers but, what should we do to get feedback or merge that PR? It has been a while and I kind of need that improvement too for my project 👍

**Comment by tadhgpearson** [comment]
This functionality would be really useful (for me anyway!) but this PR's been open for a long time. What is the barrier to merging this?

**Comment by ennru** [comment]
We do not intend to extend the functionality of "Typesafe Config" further.
See https://github.com/lightbend/config#maintained-by

**Pull request closed without merging**
